base_url: /
domain: daker.me
author: Adnane Belmadiaf
description: Blog of Adnane Belmadiaf Front-end Developer based in Morocco.
email: daker@ubuntu.com
title: Adnane Belmadiaf's Blog - Front-end Developer
date_format: "%B %d, %Y"
post_limit: 15
posts_url: /<year>/<month>/<title>.html
feed: true
archives_url: /archives/
jinja:
    extensions:
        - jinja2.ext.loopcontrols
tag_layout: tag.html
tags_url: /tags/
pygmentize: false
