base_url: /
domain: daker.me
author: Adnane Belmadiaf
description: Random thoughts on code, life, and future!
email: daker@ubuntu.com
title: Adnane Belmadiaf's Blog
date_format: "%B %d, %Y"
post_limit: 15
posts_url: /<year>/<month>/<title>.html
feed: true
archives_url: /archives/
jinja:
    extensions:
        - jinja2.ext.loopcontrols
tag_layout: tag.html
tags_url: /tags/
pygmentize: true
